name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            echo "Pulling code"
            git pull origin main

            echo "Maintenance mode"
            /www/server/php/84/bin/php artisan down || true

            echo "Install dependencies"
            composer install --no-dev --optimize-autoloader

            echo "Run migration"
            /www/server/php/84/bin/php artisan migrate --force

            echo "Clear and cache"
            /www/server/php/84/bin/php artisan optimize:clear
            /www/server/php/84/bin/php artisan optimize

            echo "Fix permission"
            chown -R www:www storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache

            echo "App live"
            /www/server/php/84/bin/php artisan up
